import io
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT

def generate_evidence_pdf(scan_result: dict) -> bytes:
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor('#CC0000'),
        spaceAfter=6,
        alignment=TA_CENTER
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#666666'),
        spaceAfter=4,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=colors.HexColor('#CC0000'),
        spaceBefore=16,
        spaceAfter=8,
        borderPad=4
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#333333'),
        spaceAfter=4,
        leading=14
    )

    letter_style = ParagraphStyle(
        'LetterBody',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#222222'),
        spaceAfter=4,
        leading=13,
        leftIndent=10
    )

    story = []
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    email = scan_result.get('email', 'Unknown')
    risk_score = scan_result.get('risk_score', 0)
    shadow_profile = scan_result.get('shadow_profile', {})
    resolved_companies = scan_result.get('resolved_companies', [])
    breached_companies = scan_result.get('breached_companies', [])
    legal_letters = scan_result.get('legal_letters', [])
    consent_expiry = scan_result.get('consent_expiry', [])

    # ─────────────────────────────────────────
    # COVER PAGE
    # ─────────────────────────────────────────
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("SHADOWTRACE", title_style))
    story.append(Paragraph("Digital Privacy Evidence Bundle", subtitle_style))
    story.append(Paragraph("Autonomous Privacy Enforcement Report", subtitle_style))
    story.append(Spacer(1, 0.2*inch))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#CC0000')))
    story.append(Spacer(1, 0.2*inch))

    # Cover details table
    cover_data = [
        ["Generated For:", email],
        ["Generated On:", timestamp],
        ["Risk Score:", f"{risk_score}/100"],
        ["Exposure Level:", shadow_profile.get('exposure_level', 'Unknown')],
        ["Companies Found:", str(len(resolved_companies))],
        ["Breaches Detected:", str(len(breached_companies))],
        ["Legal Letters:", str(len(legal_letters))],
    ]

    cover_table = Table(cover_data, colWidths=[2*inch, 4*inch])
    cover_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#CC0000')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#333333')),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#F9F9F9'), colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DDDDDD')),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 0.3*inch))

    # Legal disclaimer (UPDATED TO 2023)
    disclaimer = "This document was generated by ShadowTrace Autonomous Privacy Agent. All breach data is sourced from HaveIBeenPwned public database. Legal letters cite the Digital Personal Data Protection Act 2023. This report is intended for personal privacy enforcement use only."
    story.append(Paragraph(disclaimer, ParagraphStyle('disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.HexColor('#999999'), alignment=TA_CENTER)))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#DDDDDD')))

    # ─────────────────────────────────────────
    # SECTION 1 — RISK SUMMARY
    # ─────────────────────────────────────────
    story.append(Paragraph("Section 1 — Risk Summary", heading_style))

    risk_color = '#CC0000' if risk_score >= 70 else '#FF6600' if risk_score >= 40 else '#009900'
    story.append(Paragraph(f"<b>Overall Risk Score: <font color='{risk_color}'>{risk_score}/100</font></b>", body_style))
    story.append(Paragraph(f"<b>Exposure Level:</b> {shadow_profile.get('exposure_level', 'Unknown')}", body_style))
    story.append(Paragraph(f"<b>Primary Threat:</b> {scan_result.get('predictive_score', {}).get('primary_threat', 'Unknown')}", body_style))
    story.append(Paragraph(f"<b>Attack Probability (Next 6 Months):</b> {scan_result.get('predictive_score', {}).get('probability_percentage', 0)}%", body_style))
    story.append(Paragraph(f"<b>City Detected:</b> {shadow_profile.get('city', 'Unknown')}", body_style))

    sensitive = shadow_profile.get('sensitive_companies', [])
    if sensitive:
        story.append(Paragraph(f"<b>Sensitive Companies:</b> {', '.join(sensitive)}", body_style))

    leaked_passwords = shadow_profile.get('leaked_passwords', [])
    if leaked_passwords:
        story.append(Paragraph(f"<b>Leaked Passwords Found:</b>", body_style))
        for lp in leaked_passwords:
            story.append(Paragraph(f"  • {lp.get('source')} breach ({lp.get('year')}) — {lp.get('type')}", body_style))

    # ─────────────────────────────────────────
    # SECTION 2 — COMPANIES HOLDING YOUR DATA
    # ─────────────────────────────────────────
    story.append(Paragraph("Section 2 — Companies Holding Your Data", heading_style))
    story.append(Paragraph(f"Total companies identified: {len(resolved_companies)}", body_style))
    story.append(Spacer(1, 0.1*inch))

    if resolved_companies:
        company_data = [["Company", "Category", "Data Held", "DPO Contact"]]
        for company in resolved_companies:
            data_held = ', '.join(company.get('data_held', [])[:3])
            if len(company.get('data_held', [])) > 3:
                data_held += '...'
            company_data.append([
                company.get('company', ''),
                company.get('category', ''),
                data_held,
                company.get('dpo_email') or 'Not found'
            ])

        company_table = Table(company_data, colWidths=[1.5*inch, 1.2*inch, 2.5*inch, 1.5*inch])
        company_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CC0000')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#F9F9F9'), colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DDDDDD')),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(company_table)

    # ─────────────────────────────────────────
    # SECTION 3 — BREACH RECORDS
    # ─────────────────────────────────────────
    story.append(Paragraph("Section 3 — Breach Records", heading_style))

    if breached_companies:
        story.append(Paragraph(f"{len(breached_companies)} breach(es) detected affecting your data:", body_style))
        story.append(Spacer(1, 0.1*inch))

        breach_data = [["Company", "Breach Date", "Records Exposed", "Data Types", "Verified"]]
        for breach in breached_companies:
            data_types = ', '.join(breach.get('data_types', [])[:3])
            if len(breach.get('data_types', [])) > 3:
                data_types += '...'
            breach_data.append([
                breach.get('company', ''),
                breach.get('breach_date', 'Unknown'),
                f"{breach.get('records_exposed', 0):,}",
                data_types,
                'Yes' if breach.get('is_verified') else 'No'
            ])

        breach_table = Table(breach_data, colWidths=[1.2*inch, 1*inch, 1.2*inch, 2.5*inch, 0.7*inch])
        breach_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CC0000')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#FFF5F5'), colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DDDDDD')),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        story.append(breach_table)
    else:
        story.append(Paragraph("No breaches detected for your tracked companies.", body_style))

    # ─────────────────────────────────────────
    # SECTION 4 — CONSENT EXPIRY STATUS
    # ─────────────────────────────────────────
    story.append(Paragraph("Section 4 — Consent Expiry Status", heading_style))

    if consent_expiry:
        expiry_data = [["Company", "Status", "Section 16 Violation", "Regulator"]]
        for entry in consent_expiry:
            escalation = entry.get('escalation') or {}
            expiry_data.append([
                entry.get('company', ''),
                entry.get('expiry_status', '').replace('_', ' ').title(),
                'YES' if entry.get('section_16_violation') else 'No',
                escalation.get('regulator', 'N/A')
            ])

        expiry_table = Table(expiry_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 2*inch])
        expiry_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CC0000')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#F9F9F9'), colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DDDDDD')),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(expiry_table)

    # ─────────────────────────────────────────
    # SECTION 5 — LEGAL LETTERS
    # ─────────────────────────────────────────
    story.append(Paragraph("Section 5 — Legal Letters", heading_style))
    # (UPDATED TO 2023)
    story.append(Paragraph(f"{len(legal_letters)} formal erasure letter(s) generated under DPDP Act 2023:", body_style))
    story.append(Spacer(1, 0.1*inch))

    for i, letter in enumerate(legal_letters):
        story.append(Paragraph(
            f"<b>Letter {i+1} — {letter.get('company', '')}</b>",
            ParagraphStyle('LetterHeader', parent=styles['Normal'],
                          fontSize=10, textColor=colors.HexColor('#CC0000'),
                          spaceBefore=12, spaceAfter=4,
                          fontName='Helvetica-Bold')
        ))
        story.append(Paragraph(f"<b>To:</b> {letter.get('recipient_email') or 'No contact found — Section 16 violation'}", body_style))
        story.append(Paragraph(f"<b>Subject:</b> {letter.get('subject', '')}", body_style))
        story.append(Paragraph(f"<b>Deadline:</b> {letter.get('deadline_date', '')} (90 days)", body_style))
        story.append(Paragraph(f"<b>Escalation:</b> {letter.get('escalation_regulator', '')}", body_style))
        story.append(Spacer(1, 0.05*inch))

        body_text = letter.get('body', '').replace('\n', '<br/>')
        story.append(Paragraph(body_text, letter_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#DDDDDD')))

    # ─────────────────────────────────────────
    # FOOTER NOTE
    # ─────────────────────────────────────────
    story.append(Spacer(1, 0.3*inch))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#CC0000')))
    story.append(Spacer(1, 0.1*inch))
    # (UPDATED TO 2023)
    story.append(Paragraph(
        f"Generated by ShadowTrace Autonomous Privacy Agent | {timestamp} | DPDP Act 2023",
        ParagraphStyle('footer', parent=styles['Normal'],
                      fontSize=8, textColor=colors.HexColor('#999999'),
                      alignment=TA_CENTER)
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()